### ISSUE TITLE
Console doesn't seem to grabbing all the events from Culture Gaspesie

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-console#15]
@kmdvs Can you take a look why COnsole is not grabbing all the event from CUlture Gaspésie.  Thanks: https://console.footlight.io/events?seedurl=culturegaspesie-org

**Comment by tammy-culture** [comment]
Asked Gregory today to send a bot to read the available JSON-LD on website.

**Comment by kmdvs** [comment]
OK, I remember the issue: the calendar page has multiple dates / same location as different events... Only because it uses sometimes just a number, sometimes the title to reference those, I can't reconcile those events and gather them as one. 
To do this reconciliation, once again, a preprocessing may (I think, not obvious) be able to reconcile, but it would be better if they had the ability to multi-date their events...
