### ISSUE TITLE
What exactly are these red flags in Theatre Patriote?

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-console#26]
Hi @Kim can you take a look at these red flags please.

https://console.footlight.io/events?filter=flagged&seedurl=theatrepatriote-com

**Comment by kmdvs** [comment]
@tammy-culture 
The issue is that the calendar has identical events accessed from different URLs. 
Example: 
![Image](https://github.com/user-attachments/assets/6b67e5eb-ea80-490e-aa5c-abdf93687562)
Normally I'd just filter out /spectacle/ete/, but the structure of those URLs is legit: other URLs with similar structure are OK.

Maybe this is a one-off, and I deleted all instances. If it isn't, and can't be managed client-side, the only way to do something on our side is 
- Manual check / delete
- Scripted check / delete
- Preprocessing of URLs

**Comment by tammy-culture** [comment]
thanks
